### ISSUE TITLE
bug: reintroduced: giant value in type scale if positiveSteps contains a value >= 10

### ISSUE THREAD

**Issue by tresorama** [trys/utopia-core#5]
`1.2.0` reintrodced the resolved bug of `1.1.7` of this PR  https://github.com/trys/utopia-core/pull/2

**Comment by trys** [comment]
🤦🏻 eurgh, terrible merge there. I should've caught that GitHub mucked that up. Sorry about that!

**Comment by tresorama** [comment]
No problem at all! Thanks for fixing it quickly!!
